name: Security Snyk Workflow
on:
  push:
    branches: 
      - 'main' 
  pull_request:
    branches: 
      - '**'  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.1'  # Altere para a versão do Python do seu projeto
      - run: pip install beautifulsoup4 requests
      - name: Debug Python environment
        run: |
          python --version
          pip --version
          pip list
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
