name: Snyk Security Check
on: [push, pull_request]
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set up Snyk
        uses: snyk/actions@0.4.0
        with:
          token: SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          args: test
